name: Run Skaffold Pipeline, Deploy to Minikube Cluster and run Unguard Helm Test
on:
  pull_request:
    paths:
      - src/**
      - skaffold.yaml
      - .github/workflows/test.yaml
      - chart/**

jobs:
  lint-build-run-test-unguard:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout sources
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Check disk space
        run: df . -h

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.12.3

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs . --charts ./chart --validate-maintainers=false --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Set up Minikube
        uses: medyagh/setup-minikube@e9e035a86bbc3caea26a450bd4dbf9d0c453682e # v0.0.21
        with:
          minikube-version: 1.38.1
          addons: ingress
          start-args: --memory=6144 --cpus=4 --disk-size=20g

      - name: Cache Skaffold layers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      - name: Install and Run Skaffold and Deploy to Minikube Cluster
        run: |
          curl -fsSL -o /usr/local/bin/skaffold https://storage.googleapis.com/skaffold/releases/v2.17.1/skaffold-linux-amd64
          chmod +x /usr/local/bin/skaffold
          skaffold version
          skaffold run --skip-tests=true

      - name: Run chart-testing
        run: helm test unguard --namespace unguard --timeout 10m0s --logs
